githubRepoOwner: turnhub
githubRepoName: expression
githubHost: github.com
githubRemote: origin
githubBranch: develop
requireChecks: true
requireApproval: true
mergeMethod: rebase
mergeQueue: false
forceFetchTags: false
showPrTitlesInStack: false
branchPushIndividually: false
