defmodule Expression.V2.Context do
  @moduledoc """
  The context supplied to a function generated by `Expression.V2.Eval.compile/2`

  This will be expanded with support for more attributes that a callback function 
  can access but normal Expression evaluation can not.
  """
  defstruct vars: %{}, private: %{}

  @type t :: %__MODULE__{
          vars: map
        }

  def new(vars \\ %{}), do: %__MODULE__{vars: vars}
  def private(ctx, key, value), do: %{ctx | private: Map.put(ctx.private, key, value)}
end
